title: "Mauricio Poppe's blog"

params:
  description: "My notes about the things I learn every single day"

baseURL: "https://www.mauriciopoppe.com/"
languageCode: "en-us"

metadataFormat: 'yaml'
theme: blank

