title: "Mauricio Poppe's notes"

params:
  description: "My notes about the things I learn every day"

baseURL: "https://www.mauriciopoppe.com/"
languageCode: "en-us"

metadataFormat: 'yaml'

social:
  twitter: mauricio_poppe

