title: "Mauricio Poppe's blog"

params:
  description: "My notes about the things I learn every single day"

baseURL: "http://mauriciopoppe.com/"
languageCode: "en-us"

metadataFormat: 'yaml'
theme: blank

